### ISSUE TITLE
Breaking terms of license

### ISSUE THREAD

**Issue by liamengland1** [turkishlitecoin/PiHole#1]
Hi,

It's obvious that you've copied some of my list and are violating the terms of the MIT License. Please add a link back to my repo and/or reproduce the license in order to comply.

thanks

**Comment by turkishlitecoin** [comment]
Initial (local) upload did contain the Link and reproduction licence, but I think the list was extracted from the unique urls when put into txt file.
Will amend now. Sorry for mistake
